const localidades = [
   { nombre: "Recoleta", zona: "CABA", orientacion: "Centro" },
  { nombre: "Balvanera", zona: "CABA", orientacion: "Centro" },
  { nombre: "San Nicolás", zona: "CABA", orientacion: "Centro" },
  { nombre: "Monserrat", zona: "CABA", orientacion: "Centro" },
  { nombre: "Retiro", zona: "CABA", orientacion: "Centro" },
  { nombre: "San Telmo", zona: "CABA", orientacion: "Centro" },

  { nombre: "Palermo", zona: "CABA", orientacion: "Norte" },
  { nombre: "Belgrano", zona: "CABA", orientacion: "Norte" },
  { nombre: "Colegiales", zona: "CABA", orientacion: "Norte" },
  { nombre: "Núñez", zona: "CABA", orientacion: "Norte" },
  { nombre: "Villa Urquiza", zona: "CABA", orientacion: "Norte" },
  { nombre: "Villa Ortúzar", zona: "CABA", orientacion: "Norte" },
  { nombre: "Saavedra", zona: "CABA", orientacion: "Norte" },

  { nombre: "Caballito", zona: "CABA", orientacion: "Este" },
  { nombre: "Almagro", zona: "CABA", orientacion: "Este" },
  { nombre: "Villa Crespo", zona: "CABA", orientacion: "Este" },
  { nombre: "Boedo", zona: "CABA", orientacion: "Este" },
  { nombre: "Parque Centenario", zona: "CABA", orientacion: "Este" },

  { nombre: "Flores", zona: "CABA", orientacion: "Oeste" },
  { nombre: "Floresta", zona: "CABA", orientacion: "Oeste" },
  { nombre: "Villa del Parque", zona: "CABA", orientacion: "Oeste" },
  { nombre: "Villa Devoto", zona: "CABA", orientacion: "Oeste" },
  { nombre: "Villa Santa Rita", zona: "CABA", orientacion: "Oeste" },
  { nombre: "Monte Castro", zona: "CABA", orientacion: "Oeste" },
  { nombre: "Versalles", zona: "CABA", orientacion: "Oeste" },
  { nombre: "Villa Luro", zona: "CABA", orientacion: "Oeste" },

  { nombre: "Parque Patricios", zona: "CABA", orientacion: "Sur" },
  { nombre: "La Boca", zona: "CABA", orientacion: "Sur" },
  { nombre: "Barracas", zona: "CABA", orientacion: "Sur" },
  { nombre: "Nueva Pompeya", zona: "CABA", orientacion: "Sur" },
  { nombre: "Villa Lugano", zona: "CABA", orientacion: "Sur" },
  { nombre: "Villa Soldati", zona: "CABA", orientacion: "Sur" },
  { nombre: "Villa Riachuelo", zona: "CABA", orientacion: "Sur" },
  { nombre: "Parque Chacabuco", zona: "CABA", orientation: "Sur" },
  { nombre: "Parque Avellaneda", zona: "CABA", orientacion: "Sur" },
    { nombre: "CABA", zona: "CABA", orientacion: "Centro" },
   { nombre: "Avellaneda", zona: "Z1", orientacion: "Sur" },
  { nombre: "Lanús", zona: "Z1", orientacion: "Sur" },
  { nombre: "Lomas de Zamora", zona: "Z1", orientacion: "Sur" },
  { nombre: "Morón", zona: "Z1", orientacion: "Oeste" },
  { nombre: "Hurlingham", zona: "Z1", orientacion: "Oeste" },
  { nombre: "Ituzaingó", zona: "Z1", orientacion: "Oeste" },
  { nombre: "San Isidro", zona: "Z1", orientacion: "Norte" },
  { nombre: "Vicente López", zona: "Z1", orientacion: "Norte" },
  { nombre: "San Fernando", zona: "Z1", orientacion: "Norte" },
  { nombre: "San Martín", zona: "Z1", orientacion: "Norte" },
  { nombre: "3 de Febrero", zona: "Z1", orientacion: "Norte" },
  { nombre: "La Matanza Norte", zona: "Z1", orientacion: "Oeste" },

  // Z2 (Segundo Cordón)
  { nombre: "Quilmes", zona: "Z2", orientacion: "Sur" },
  { nombre: "Florencio Varela", zona: "Z2", orientacion: "Sur" },
  { nombre: "Esteban Echeverría", zona: "Z2", orientacion: "Sur" },
  { nombre: "Ezeiza", zona: "Z2", orientacion: "Oeste" },
  { nombre: "José C. Paz", zona: "Z2", orientacion: "Oeste" },
  { nombre: "San Miguel", zona: "Z2", orientacion: "Oeste" },
  { nombre: "Malvinas Argentinas", zona: "Z2", orientacion: "Norte" },
  { nombre: "Escobar", zona: "Z2", orientacion: "Norte" },
  { nombre: "Tigre", zona: "Z2", orientacion: "Norte" },
  { nombre: "Almirante Brown", zona: "Z2", orientacion: "Sur" },
  { nombre: "La Matanza Sur", zona: "Z2", orientacion: "Oeste" },

  // Z3 (Tercer Cordón)
  { nombre: "Berisso", zona: "Z3", orientacion: "Sur" },
  { nombre: "Ensenada", zona: "Z3", orientacion: "Sur" },
  { nombre: "La Plata (Centro)", zona: "Z3", orientacion: "Sur" },
  { nombre: "La Plata Norte", zona: "Z3", orientacion: "Sur" },
  { nombre: "La Plata Oeste", zona: "Z3", orientacion: "Sur" },
  { nombre: "Berazategui", zona: "Z3", orientacion: "Sur" },
  { nombre: "Cañuelas", zona: "Z3", orientacion: "Oeste" },
  { nombre: "Marcos Paz", zona: "Z3", orientacion: "Oeste" },
  { nombre: "Merlo", zona: "Z3", orientacion: "Oeste" },
  { nombre: "Moreno", zona: "Z3", orientacion: "Oeste" },
  { nombre: "Luján", zona: "Z3", orientacion: "Oeste" },
  { nombre: "Campana", zona: "Z3", orientacion: "Norte" },
  { nombre: "Zárate", zona: "Z3", orientacion: "Norte" },
  { nombre: "Villa Rosa", zona: "Z3", orientacion: "Norte" },
  { nombre: "Del Viso", zona: "Z3", orientacion: "Norte" },
  { nombre: "Derqui", zona: "Z3", orientacion: "Norte" },
  { nombre: "Guernica", zona: "Z3", orientacion: "Sur" },
  { nombre: "San Vicente", zona: "Z3", orientacion: "Sur" },
  { nombre: "Nordelta", zona: "Z3", orientacion: "Norte" },
  { nombre: "Ingeniero Maschwitz", zona: "Z3", orientacion: "Norte" },
  { nombre: "Pilar", zona: "Z3", orientacion: "Norte" },
  { nombre: "General Rodríguez", zona: "Z3", orientacion: "Oeste" },
];





export default  localidades;