const localidades = [
     { nombre: "CABA", zona: "CABA" },
  { nombre: "Avellaneda", zona: "Primer Cordón" },
  { nombre: "Lanús", zona: "Primer Cordón" },
  { nombre: "Lomas de Zamora", zona: "Primer Cordón" },
  { nombre: "Morón", zona: "Primer Cordón" },
  { nombre: "Hurlingham", zona: "Primer Cordón" },
  { nombre: "Ituzaingó", zona: "Primer Cordón" },
  { nombre: "San Isidro", zona: "Primer Cordón" },
  { nombre: "Vicente López", zona: "Primer Cordón" },
  { nombre: "San Fernando", zona: "Primer Cordón" },
  { nombre: "San Martín", zona: "Primer Cordón" },
  { nombre: "La Matanza Norte", zona: "Primer Cordón" },

  { nombre: "Quilmes", zona: "Segundo Cordón" },
  { nombre: "Florencio Varela", zona: "Segundo Cordón" },
  { nombre: "Esteban Echeverría", zona: "Segundo Cordón" },
  { nombre: "Ezeiza", zona: "Segundo Cordón" },
  { nombre: "José C. Paz", zona: "Segundo Cordón" },
  { nombre: "San Miguel", zona: "Segundo Cordón" },
  { nombre: "Malvinas Argentinas", zona: "Segundo Cordón" },
  { nombre: "Escobar", zona: "Segundo Cordón" },
  { nombre: "Tigre", zona: "Segundo Cordón" },
  { nombre: "Almirante Brown", zona: "Segundo Cordón" },
  { nombre: "La Matanza Sur", zona: "Segundo Cordón" },

  { nombre: "Berisso", zona: "Tercer Cordón" },
  { nombre: "Ensenada", zona: "Tercer Cordón" },
  { nombre: "La Plata (Centro)", zona: "Tercer Cordón" },
  { nombre: "La Plata Norte", zona: "Tercer Cordón" },
  { nombre: "La Plata Oeste", zona: "Tercer Cordón" },
  { nombre: "Berazategui", zona: "Tercer Cordón" },
  { nombre: "Cañuelas", zona: "Tercer Cordón" },
  { nombre: "Marcos Paz", zona: "Tercer Cordón" },
  { nombre: "Merlo", zona: "Tercer Cordón" },
  { nombre: "Moreno", zona: "Tercer Cordón" },
  { nombre: "Luján", zona: "Tercer Cordón" },
  { nombre: "Campana", zona: "Tercer Cordón" },
  { nombre: "Zárate", zona: "Tercer Cordón" },
  { nombre: "Villa Rosa", zona: "Tercer Cordón" },
  { nombre: "Del Viso", zona: "Tercer Cordón" },
  { nombre: "Derqui", zona: "Tercer Cordón" },
  { nombre: "Guernica", zona: "Tercer Cordón" },
  { nombre: "San Vicente", zona: "Tercer Cordón" },
  { nombre: "Nordelta", zona: "Tercer Cordón" },
  { nombre: "Ingeniero Maschwitz", zona: "Tercer Cordón" },
  { nombre: "Pilar", zona: "Tercer Cordón" },
  { nombre: "General Rodríguez", zona: "Tercer Cordón" },
];

export default localidades