const localidades = [
    { nombre: "CABA", zona: "CABA", orientacion: "Centro" },
  { nombre: "Avellaneda", zona: "Primer Cordón", orientacion: "Sur" },
{ nombre: "Lanús", zona: "Primer Cordón", orientacion: "Sur" },
{ nombre: "Lomas de Zamora", zona: "Primer Cordón", orientacion: "Sur" },
{ nombre: "Morón", zona: "Primer Cordón", orientacion: "Oeste" },
{ nombre: "Hurlingham", zona: "Primer Cordón", orientacion: "Oeste" },
{ nombre: "Ituzaingó", zona: "Primer Cordón", orientacion: "Oeste" },
{ nombre: "San Isidro", zona: "Primer Cordón", orientacion: "Norte" },
{ nombre: "Vicente López", zona: "Primer Cordón", orientacion: "Norte" },
{ nombre: "San Fernando", zona: "Primer Cordón", orientacion: "Norte" },
{ nombre: "San Martín", zona: "Primer Cordón", orientacion: "Norte" },
{ nombre: "3 de Febrero", zona: "Primer Cordón", orientacion: "Norte" },
{ nombre: "La Matanza Norte", zona: "Primer Cordón", orientacion: "Oeste" },

 { nombre: "Quilmes", zona: "Segundo Cordón", orientacion: "Sur" },
{ nombre: "Florencio Varela", zona: "Segundo Cordón", orientacion: "Sur" },
{ nombre: "Esteban Echeverría", zona: "Segundo Cordón", orientacion: "Sur" },
{ nombre: "Ezeiza", zona: "Segundo Cordón", orientacion: "Oeste" },
{ nombre: "José C. Paz", zona: "Segundo Cordón", orientacion: "Oeste" },
{ nombre: "San Miguel", zona: "Segundo Cordón", orientacion: "Oeste" },
{ nombre: "Malvinas Argentinas", zona: "Segundo Cordón", orientacion: "Norte" },
{ nombre: "Escobar", zona: "Segundo Cordón", orientacion: "Norte" },
{ nombre: "Tigre", zona: "Segundo Cordón", orientacion: "Norte" },
{ nombre: "Almirante Brown", zona: "Segundo Cordón", orientacion: "Sur" },
{ nombre: "La Matanza Sur", zona: "Segundo Cordón", orientacion: "Oeste" },

 { nombre: "Berisso", zona: "Tercer Cordón", orientacion: "Sur" },
{ nombre: "Ensenada", zona: "Tercer Cordón", orientacion: "Sur" },
{ nombre: "La Plata (Centro)", zona: "Tercer Cordón", orientacion: "Sur" },
{ nombre: "La Plata Norte", zona: "Tercer Cordón", orientacion: "Sur" },
{ nombre: "La Plata Oeste", zona: "Tercer Cordón", orientacion: "Sur" },
{ nombre: "Berazategui", zona: "Tercer Cordón", orientacion: "Sur" },
{ nombre: "Cañuelas", zona: "Tercer Cordón", orientacion: "Oeste" },
{ nombre: "Marcos Paz", zona: "Tercer Cordón", orientacion: "Oeste" },
{ nombre: "Merlo", zona: "Tercer Cordón", orientacion: "Oeste" },
{ nombre: "Moreno", zona: "Tercer Cordón", orientacion: "Oeste" },
{ nombre: "Luján", zona: "Tercer Cordón", orientacion: "Oeste" },
{ nombre: "Campana", zona: "Tercer Cordón", orientacion: "Norte" },
{ nombre: "Zárate", zona: "Tercer Cordón", orientacion: "Norte" },
{ nombre: "Villa Rosa", zona: "Tercer Cordón", orientacion: "Norte" },
{ nombre: "Del Viso", zona: "Tercer Cordón", orientacion: "Norte" },
{ nombre: "Derqui", zona: "Tercer Cordón", orientacion: "Norte" },
{ nombre: "Guernica", zona: "Tercer Cordón", orientacion: "Sur" },
{ nombre: "San Vicente", zona: "Tercer Cordón", orientacion: "Sur" },
{ nombre: "Nordelta", zona: "Tercer Cordón", orientacion: "Norte" },
{ nombre: "Ingeniero Maschwitz", zona: "Tercer Cordón", orientacion: "Norte" },
{ nombre: "Pilar", zona: "Tercer Cordón", orientacion: "Norte" },
{ nombre: "General Rodríguez", zona: "Tercer Cordón", orientacion: "Oeste" },
];





export default  localidades;